import { describe, expect, it } from 'vitest';
import { generateIdentity, type IdentityOptions, type IdentityResult } from './oracleIdentity';

const base: IdentityOptions = {
  table: 'siparis',
  column: 'siparis_id',
  version: '11g',
  startWith: 1,
  allowExplicit: true,
};

const run = (patch: Partial<IdentityOptions> = {}): IdentityResult => {
  const result = generateIdentity({ ...base, ...patch });
  if (!result.ok) throw new Error(`beklenmeyen hata: ${result.error}`);
  return result.value;
};

const warnings = (patch: Partial<IdentityOptions> = {}) => run(patch).warnings.map((w) => w.key);

describe('11g — sequence ve trigger', () => {
  it('tam betiği üretir', () => {
    expect(run().sql).toBe(
      [
        'CREATE SEQUENCE SEQ_SIPARIS',
        '  START WITH 1',
        '  INCREMENT BY 1',
        '  CACHE 20',
        '  NOCYCLE;',
        '',
        'CREATE OR REPLACE TRIGGER TRG_SIPARIS_BI',
        'BEFORE INSERT ON SIPARIS',
        'FOR EACH ROW',
        'WHEN (NEW.SIPARIS_ID IS NULL)',
        'BEGIN',
        '  SELECT SEQ_SIPARIS.NEXTVAL INTO :NEW.SIPARIS_ID FROM DUAL;',
        'END;',
        '/',
      ].join('\n'),
    );
  });

  it('adları büyük harfe çevirir', () => {
    expect(run().names).toEqual({ sequence: 'SEQ_SIPARIS', trigger: 'TRG_SIPARIS_BI' });
  });

  it('başlangıç değerini uygular', () => {
    expect(run({ startWith: 1000 }).sql).toContain('START WITH 1000');
  });

  it('elle anahtar verilmesine izin verilmezse WHEN koşulu düşer', () => {
    // Koşul olmadan açıkça verilen anahtar sessizce eziliyor — veri
    // taşımayı bozan tam olarak bu.
    expect(run({ allowExplicit: false }).sql).not.toContain('WHEN (');
  });

  it('sequence boşluklarını hatırlatır', () => {
    expect(warnings()).toContain('sequenceGaps');
  });
});

describe('12c — IDENTITY kolon', () => {
  it('trigger yerine ALTER TABLE üretir', () => {
    const sql = run({ version: '12c' }).sql;
    expect(sql).toContain('GENERATED BY DEFAULT ON NULL AS IDENTITY');
    expect(sql).not.toContain('CREATE TRIGGER');
  });

  it('IDENTITY’nin tercih edilmesi gerektiğini söyler', () => {
    expect(warnings({ version: '12c' })).toContain('identityPreferred');
  });
});

describe('tanımlayıcı sınırı', () => {
  it('11g’de 30 karakteri aşan ÜRETİLEN adı bildirir', () => {
    // Tablo adı sınırın altında ama SEQ_ öneki ve _BI soneki İKİSİNİ birden
    // aşırıyor — sorun tabloda değil, üretilen adlarda.
    const long = 'kurum_disi_sevk_talep_kaydi';
    const details = run({ table: long })
      .warnings.filter((w) => w.key === 'nameTooLong')
      .map((w) => w.detail);

    expect(long.length).toBeLessThan(30);
    expect(details).toEqual([
      'SEQ_KURUM_DISI_SEVK_TALEP_KAYDI (31 > 30)',
      'TRG_KURUM_DISI_SEVK_TALEP_KAYDI_BI (34 > 30)',
    ]);
  });

  it('12c’de aynı ad sorun değil', () => {
    expect(warnings({ table: 'kurum_disi_sevk_talep_kaydi', version: '12c' })).not.toContain(
      'nameTooLong',
    );
  });

  it('geçersiz tanımlayıcıyı bildirir', () => {
    const found = run({ table: '1siparis' }).warnings.find((w) => w.key === 'invalidIdentifier');
    expect(found?.detail).toBe('table: 1SIPARIS');
  });

  it('geçerli tanımlayıcıda uyarı yok', () => {
    expect(warnings()).not.toContain('invalidIdentifier');
  });
});

describe('girdi doğrulama', () => {
  it('boş tablo adı hata döner', () => {
    expect(generateIdentity({ ...base, table: '  ' })).toEqual({ ok: false, error: 'identityEmpty' });
  });

  it('boş kolon adı hata döner', () => {
    expect(generateIdentity({ ...base, column: '' })).toEqual({ ok: false, error: 'identityEmpty' });
  });
});
