import { err, ok, type ToolResult } from '../types';

/**
 * Oracle'da otomatik artan birincil anahtar üretir.
 *
 * 12c'den önce `IDENTITY` kolon YOK: bir `SEQUENCE` ve onu okuyan bir
 * `BEFORE INSERT` tetikleyicisi yazmak gerekiyor. Elle yazarken iki şey
 * sürekli unutuluyor ve ikisi de sonradan pahalıya patlıyor —
 * `WHEN (NEW.x IS NULL)` koşulu (onsuz veri taşırken açıkça verilen
 * anahtarlar sessizce eziliyor) ve tanımlayıcıların 30 karakter sınırı.
 */

/** Sürüm yalnızca iki şeyi değiştiriyor: üretilen kod ve ad uzunluğu sınırı. */
export const VERSIONS = ['11g', '12c'] as const;
export type OracleVersion = (typeof VERSIONS)[number];

/**
 * Tanımlayıcı uzunluk sınırı.
 *
 * 11g'de 30 karakter — ve bu sınır tabloya değil, ÜRETİLEN adlara takılıyor:
 * `SEQ_` öneki ve `_BI` soneki tablo adının üstüne biniyor. Hata
 * (`ORA-00972: identifier is too long`) yalnızca betik çalıştırıldığında
 * çıkıyor, yani genelde deploy sırasında.
 */
const NAME_LIMIT: Record<OracleVersion, number> = { '11g': 30, '12c': 128 };

/** Tırnaksız Oracle tanımlayıcısı: harfle başlar, harf/rakam/`_$#` sürer. */
const IDENTIFIER = /^[A-Za-z][A-Za-z0-9_$#]*$/;

export interface IdentityOptions {
  table: string;
  column: string;
  version: OracleVersion;
  startWith: number;
  /**
   * `WHEN (NEW.x IS NULL)` koşulu. Açıkken elle verilen anahtar korunuyor —
   * veri taşımanın ve testin çalışabilmesi için gereken davranış.
   */
  allowExplicit: boolean;
}

export interface IdentityWarningKey {
  key: 'nameTooLong' | 'invalidIdentifier' | 'sequenceGaps' | 'identityPreferred';
  /** Çevrilmeyen ek bilgi: sorunlu ad, uzunluk. */
  detail?: string;
}

export interface IdentityResult {
  sql: string;
  warnings: IdentityWarningKey[];
  /** Üretilen nesne adları — arayüz bunları ayrıca gösteriyor. */
  names: { sequence: string; trigger: string };
}

const upper = (value: string) => value.trim().toUpperCase();

export function generateIdentity(options: IdentityOptions): ToolResult<IdentityResult> {
  const table = upper(options.table);
  const column = upper(options.column);

  if (table === '' || column === '') return err('identityEmpty');

  const warnings: IdentityWarningKey[] = [];
  const limit = NAME_LIMIT[options.version];

  for (const [label, value] of [
    ['table', table],
    ['column', column],
  ] as const) {
    if (!IDENTIFIER.test(value)) {
      warnings.push({ key: 'invalidIdentifier', detail: `${label}: ${value}` });
    }
  }

  const sequence = `SEQ_${table}`;
  const trigger = `TRG_${table}_BI`;
  const names = { sequence, trigger };

  for (const name of [sequence, trigger, table, column]) {
    if (name.length > limit) {
      warnings.push({ key: 'nameTooLong', detail: `${name} (${name.length} > ${limit})` });
    }
  }

  if (options.version === '12c') {
    warnings.push({ key: 'identityPreferred' });
    return ok({
      names,
      warnings,
      sql: [
        `ALTER TABLE ${table}`,
        `  MODIFY (${column} NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH ${options.startWith});`,
      ].join('\n'),
    });
  }

  warnings.push({ key: 'sequenceGaps' });

  /* `SELECT … INTO` biçimi kullanılıyor, `:NEW.x := seq.NEXTVAL` değil:
     ikincisi 11g'de çalışıyor ama daha eski sürümlerde çalışmıyor ve
     üretilen betik çoğu zaman birkaç ortamda birden koşuyor. */
  const body = [
    `CREATE SEQUENCE ${sequence}`,
    `  START WITH ${options.startWith}`,
    '  INCREMENT BY 1',
    '  CACHE 20',
    '  NOCYCLE;',
    '',
    `CREATE OR REPLACE TRIGGER ${trigger}`,
    `BEFORE INSERT ON ${table}`,
    'FOR EACH ROW',
  ];

  if (options.allowExplicit) body.push(`WHEN (NEW.${column} IS NULL)`);

  body.push(
    'BEGIN',
    `  SELECT ${sequence}.NEXTVAL INTO :NEW.${column} FROM DUAL;`,
    'END;',
    '/',
  );

  return ok({ names, warnings, sql: body.join('\n') });
}
